export default [
  {
    portfolioCode: 'TP01',
    riskPreference: '공격투자형',
    themeName: '배당특급(공격투자형)',
    composition: [
      { category: '국내채권', percentage: 0 },
      { category: '해외채권', percentage: 30 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 70 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP02',
    riskPreference: '공격투자형',
    themeName: '가치주 대반란(공격투자형)',
    composition: [
      { category: '국내채권', percentage: 0 },
      { category: '해외채권', percentage: 20 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 80 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP03',
    riskPreference: '공격투자형',
    themeName: '캡틴 아메리카(공격투자형)',
    composition: [
      { category: '국내채권', percentage: 0 },
      { category: '해외채권', percentage: 25 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 75 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP04',
    riskPreference: '공격투자형',
    themeName: 'ESG 워너비',
    composition: [
      { category: '국내채권', percentage: 0 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 100 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP05',
    riskPreference: '공격투자형',
    themeName: '지금은 IT시대',
    composition: [
      { category: '국내채권', percentage: 0 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 100 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP06',
    riskPreference: '공격투자형',
    themeName: '글로벌 대장주',
    composition: [
      { category: '국내채권', percentage: 0 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 100 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP07',
    riskPreference: '공격투자형',
    themeName: '대체불가 실물투자',
    composition: [
      { category: '국내채권', percentage: 20 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 80 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP08',
    riskPreference: '공격투자형',
    themeName: '전지적 펀드시점',
    composition: [
      { category: '국내채권', percentage: 0 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 100 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP09',
    riskPreference: '공격투자형',
    themeName: 'G2',
    composition: [
      { category: '국내채권', percentage: 30 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 35 },
      { category: '신흥주식', percentage: 35 },
    ],
  },
  {
    portfolioCode: 'TP10',
    riskPreference: '공격투자형',
    themeName: '글로벌 자산배분(공격투자형)',
    composition: [
      { category: '국내채권', percentage: 30 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 70 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP11',
    riskPreference: '공격투자형',
    themeName: '글로벌 바겐세일',
    composition: [
      { category: '국내채권', percentage: 0 },
      { category: '해외채권', percentage: 20 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 40 },
      { category: '신흥주식', percentage: 40 },
    ],
  },
  {
    portfolioCode: 'TP12',
    riskPreference: '공격투자형',
    themeName: '사계절 자산배분',
    composition: [
      { category: '국내채권', percentage: 55 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 37 },
      { category: '신흥주식', percentage: 8 },
    ],
  },
  {
    portfolioCode: 'TP13',
    riskPreference: '공격투자형',
    themeName: '영구 자산배분',
    composition: [
      { category: '국내채권', percentage: 25 },
      { category: '해외채권', percentage: 25 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 25 },
      { category: '신흥주식', percentage: 25 },
    ],
  },
  {
    portfolioCode: 'TP14',
    riskPreference: '적극투자형',
    themeName: '펀린이 컬렉션(적극투자형)',
    composition: [
      { category: '국내채권', percentage: 20 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 80 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP15',
    riskPreference: '적극투자형',
    themeName: '배당특급(적극투자형)',
    composition: [
      { category: '국내채권', percentage: 30 },
      { category: '해외채권', percentage: 20 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 50 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP16',
    riskPreference: '적극투자형',
    themeName: '가치주 대반란(적극투자형)',
    composition: [
      { category: '국내채권', percentage: 20 },
      { category: '해외채권', percentage: 30 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 50 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP17',
    riskPreference: '적극투자형',
    themeName: '캡틴 아메리카(적극투자형)',
    composition: [
      { category: '국내채권', percentage: 20 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 80 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP18',
    riskPreference: '적극투자형',
    themeName: '글로벌 자산배분(적극투자형)',
    composition: [
      { category: '국내채권', percentage: 20 },
      { category: '해외채권', percentage: 20 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 60 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP19',
    riskPreference: '위험중립형',
    themeName: '펀린이 컬렉션(위험중립형)',
    composition: [
      { category: '국내채권', percentage: 20 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 80 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP20',
    riskPreference: '위험중립형',
    themeName: '배당특급(위험중립형)',
    composition: [
      { category: '국내채권', percentage: 30 },
      { category: '해외채권', percentage: 50 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 20 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP21',
    riskPreference: '위험중립형',
    themeName: '가치주 대반란(위험중립형)',
    composition: [
      { category: '국내채권', percentage: 20 },
      { category: '해외채권', percentage: 30 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 50 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP22',
    riskPreference: '안정추구형',
    themeName: '수퍼세이브(안정추구형)',
    composition: [
      { category: '국내채권', percentage: 100 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 0 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP23',
    riskPreference: '안정추구형',
    themeName: '펀린이 컬렉션(안정추구형)',
    composition: [
      { category: '국내채권', percentage: 100 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 0 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP24',
    riskPreference: '안정형',
    themeName: '수퍼세이브(안정형)',
    composition: [
      { category: '국내채권', percentage: 100 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 0 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
  {
    portfolioCode: 'TP25',
    riskPreference: '안정형',
    themeName: '펀린이 컬렉션(안정형)',
    composition: [
      { category: '국내채권', percentage: 100 },
      { category: '해외채권', percentage: 0 },
      { category: '국내주식', percentage: 0 },
      { category: '선진주식', percentage: 0 },
      { category: '신흥주식', percentage: 0 },
    ],
  },
];
